#!/bin/sh

chmod 644 /sys/class/backlight/intel_backlight/brightness
max=`cat /sys/class/backlight/intel_backlight/max_brightness`

echo $max > /sys/class/backlight/intel_backlight/brightness
chmod 444 /sys/class/backlight/intel_backlight/brightness
