#!/bin/sh

chmod 644 /sys/class/backlight/intel_backlight/brightness
current=`cat /sys/class/backlight/intel_backlight/brightness`
max=`cat /sys/class/backlight/intel_backlight/max_brightness`

if [ $(($current+10)) -lt $max ] 
then
  new=$(($current+10))
else
  new=$max
fi

echo Current: $current
echo Max: $max
echo New:$new

echo $new > /sys/class/backlight/intel_backlight/brightness
chmod 444 /sys/class/backlight/intel_backlight/brightness
