#!/bin/bash

#Power table taken from
#https://www.spinics.net/lists/linux-input/msg70450.html

now="$(cat /sys/class/power_supply/hidpp_battery_0/voltage_now)"

IFS=$'\n'
for line in $(tac "$HOME/.scripts/.Logitech_g703_battery_levels")
do
  volt="$(bc -l <<< "1000000*${line%%" "*}")"
  voltint="${volt%%.*}"
  if [ "$now" -lt "$voltint" ]
  then
    echo "${line#*" "}"
    exit 0
  fi
done
exit 1

